[package]
authors = ["Kornel <kornel@geekhood.net>"]
categories = ["multimedia::video", "command-line-utilities"]
description = "pngquant-based GIF maker for nice-looking animGIFs"
documentation = "https://docs.rs/gifski"
homepage = "https://gif.ski"
include = ["README.md", "Cargo.toml", "src/*.rs", "src/bin/*.rs"]
keywords = ["gif", "encoder", "converter", "maker", "gifquant"]
license = "AGPL-3.0+"
name = "gifski"
readme = "README.md"
repository = "https://github.com/ImageOptim/gifski"
version = "0.2.0"

[[bin]]
name = "gifski"
doctest = false

[dependencies]
clap = "2.26.2"
error-chain = "0.11.0"
gif = "0.9.2"
gif-dispose = "2.0.0"
imagequant = "2.11.4"
imgref = "1.2.2"
lodepng = "2.0.2"
pbr = "1.0.0"
rayon = "0.8.2"
rgb = "0.7.2"
threadpool = "1.7.0"

[lib]
path = "src/lib.rs"

[profile.dev]
opt-level = 1
