[package]
authors = ["Kornel <kornel@geekhood.net>"]
categories = ["multimedia::video", "command-line-utilities"]
description = "pngquant-based GIF maker for nice-looking animGIFs"
documentation = "https://docs.rs/gifski"
homepage = "https://gif.ski"
include = ["README.md", "Cargo.toml", "src/*.rs", "src/bin/*.rs"]
keywords = ["gif", "encoder", "converter", "maker", "gifquant"]
license = "AGPL-3.0+"
name = "gifski"
readme = "README.md"
repository = "https://github.com/ImageOptim/gifski"
version = "0.4.0"


[package.metadata.deb]
features = ["openmp"]

[[bin]]
doctest = false
name = "gifski"

[dependencies]
clap = "2.26.2"
error-chain = "0.11.0"
gif = "0.9.2"
gif-dispose = "2.0.1"
imagequant = "2.11.5"
imgref = "1.2.2"
lodepng = "2.0.4"
pbr = "1.0.0"
rayon = "0.8.2"
resize = "0.3.0"
rgb = "0.8.1"
threadpool = "1.7.0"

[dependencies.ffmpeg]
optional = true
git = "https://github.com/pornel/rust-ffmpeg.git"
features = ["codec", "format", "filter", "software-resampling", "software-scaling", "resampling" ]

[features]
default-features = []
openmp = ["imagequant/openmp"]
video = ["ffmpeg"]

[lib]
path = "src/lib.rs"

[profile.dev]
opt-level = 1

[profile.release]
panic = "abort"
lto = true
